// For QuizWipContext
export const SET_LOADING = "SET_LOADING";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_CURRENT_TASK = "SET_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const FILTER_TASK = "FILTER_TASK";
export const CLEAR_FILTER_TASK = "CLEAR_FILTER_TASK";
export const SET_BACKLOGGED_TO_STARTED = "SET_BACKLOGGED_TO_STARTED";

export const SET_CURRENT_FILTER_SELECT = "SET_CURRENT_FILTER_SELECT";
export const CLEAR_CURRENT_FILTER_SELECT = "CLEAR_CURRENT_FILTER_SELECT";
export const SET_CURRENT_STATE_CAT = "SET_CURRENT_STATE_CAT";

export const DELETE_FINAL_ROW = "DELETE_FINAL_ROW";

// For Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// For alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";